### ISSUE TITLE
Error: Command failed: ./scripts/get-version.sh (windows 11)

### ISSUE THREAD

**Issue by DzunN86** [calvincchan/react-version-checker#1]

**Comment by calvincchan** [comment]
Hello @DzunN86 thanks for bringing this issue to my attention. The script is in fact a shell script that runs on Linux-like systems, so I believe it can't be run on a Windows machine directly. You may try to use Docker or virtual machine to prepare yourself a local Linux dev environment. You may also try it on Codesandbox just to get an idea how it works.
